apiVersion: syml.somebugs.com/v1
kind: Schema
meta:
  name: tpc-h-customer
  type: dimension
  version: 2.17.1
  desc: >
    Customer

spec:

  target:
    kind: database
    provider: snowflake
    type: table
    spec:
      database: DEMO_DB
      schema: TPC-H
      table: CUSTOMER

  fields:

    - name: C_CUSTKEY
      type: TEXT
      dimension: retain
      constraints: ["pk", "not-null", "not-empty"]
      desc: "Unique customer KEY"


    - name: PROFILE
      type: GROUP
      dimension: overwrite
      desc: "Group of the personal customer fields"

      fields:

        - name: C_NAME
          type: TEXT
          desc: "Full customer name"

        - name: C_ADDRESS
          type: TEXT
          desc: "Customer address"

        - name: C_NATIONKEY
          type: TEXT
          desc: "Reference to nation"
          relation:
            type: reference
            target:
              schema: ./nation.syml.yml
              field: NATIONKEY

        - name: C_PHONE
          desc: "Customer phone"
          type: TEXT

        - name: C_ACCTBAL
          desc: "Account balance"
          type: DECIMAL

    - name: C_MKTSEGMENT
      type: TEXT
      dimension: overwrite
      desc: "Market segment"

    - name: C_COMMENT
      dimension: overwrite
      type: TEXT
      desc: "Customer record comment"
