version: '3.1'

services:

  syml_test_db:

    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: symltest
    ports:
      - 5432:5432
    user: root
    volumes:
      - ./data/:/docker-entrypoint-initdb.d/
      - ./data/:/data/
